### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by r-barnes** [franktakes/teexgraph#11]
Could you update the README to include a preferred citation for the software? Perhaps a paper or set of papers?

If you would like the software itself to be cited, you might consider archiving it on [Zenodo](https://zenodo.org/) so that there is a doi number.

Another route to consider is to submit the software to the [Journal of Open Source Software](https://joss.theoj.org/). This will get you peer-reviewed feedback on the usability, &c of the software, a doi number, and another peer-reviewed "publication". I'm happy to talk you through the process if that's of interest.

**Comment by franktakes** [comment]
This is a good suggestion. 
I orginally created `teexgraph` as a combination of different bits of code that I wrote during my PhD.
Never really considered giving it a reference of its own; most people appear to use it for the fast diameter computation (the CIKM 2011 paper referenced in the README).
Also, I was aware of the fact that `teexgraph` wasn't really up to software engineering standards, and therefore not as easy to reuse or integrate in other software. You obviously did some very good steps in that direction. 
So now I think it might actually make sense to give the package a reference of its own.
I'll contact you later this week to discuss this further, as I am interested in your thoughts and ideas about this!

**Comment by r-barnes** [comment]
@franktakes : I'm certainly here for the fast diameter computation! But using teexgraph as a library makes it much easier for me to incorporate that into a reproducible workflow.

#8  should make it much easier to integrate teexgraph with other software. For instance, to incorporate into a cmake-based C++ project requires only:
```text
add_subdirectory(path/to/teexgraph EXCLUDE_FROM_ALL)
target_link_libraries(your_executable_target PRIVATE teexgraphlib)
```
and Python required only
```
import pyteexgraph
```

The only thing really missing from both of these is documentation. The [DOxygen](https://www.doxygen.nl/index.html) system is pretty standard for this and pretty easy to work with.

**Comment by franktakes** [comment]
Should also use this functionality;
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files
