### ISSUE TITLE
Average distance error

### ISSUE THREAD

**Issue by franktakes** [franktakes/teexgraph#14]
Currently, the averageDistance() function in `Graph.cpp` appears broken; seemingly due to something with the OpenMP.
Until it is fixed, the average distance value can easily be derived from the summary statistics of the distanceDistribution() function in `examples.cpp`.

**Comment by r-barnes** [comment]
You should write your OpenMP as:
```
#pragma omp ... default(none) shared(xxx) private(xxx) firstprivate(xxx)
```
The `default(none)` forces all variables to be marked explicitly as shared, private, firstprivate, &c, this helps prevent situations in which a variable is being unexpectedly shared.
