### ISSUE TITLE
loadDirected stuck when reading files start with a newline '\n'

### ISSUE THREAD

**Issue by tadshi** [franktakes/teexgraph#20]
Hello! 

I was using this nice library in my research when I happened to find that the function `Graph::loadDirected` will fall into a non-terminating loop when reading a file starts with a newline. This is due to the [line 147](https://github.com/franktakes/teexgraph/blob/5990a613f122dffe8b8f0355246b592c1f2e1fe0/src/Graph.cpp#L147) in graph.cpp, which will cause line 149 to peek forever if the first character it get from fin at line 141 is '\n'.

Even though the fix is rather easy, I reckon this is an unexpected behavior so I try to report it here. Maybe there can be a patch? :)

**Comment by franktakes** [comment]
Hi @tadshi, great to hear that teexGraph is useful for your research. I did a little fix so that now it's possible to have files start with new lines (or in fact, "whitespace" in general). Happy coding!
